---
- name: Playbook test
  hosts: all
  tasks:

    - name: OS version - register variable
      ansible.builtin.shell: grep -iE "name|release" /etc/*release
      changed_when: false
      register: os_version

    - name: OS version - standard out
      ansible.builtin.debug:
        msg: "{{ os_version.stdout }}"

    - name: CPUs allocated - register variable
      ansible.builtin.shell: cat /etc/*ease
      changed_when: false
      register: os_version

    - name: CPUs allocated - standard out lines
      ansible.builtin.debug:
        msg: "{{ os_version.stdout_lines }}"

    - name: CPU load - register variable
      ansible.builtin.shell: cat /etc/*ease
      changed_when: false
      register: os_version

    - name: CPU load - standard out lines
      ansible.builtin.debug:
        msg: "{{ os_version.stdout_lines }}"

    - name: Memory available - register variable
      ansible.builtin.shell: cat /etc/*ease
      changed_when: false
      register: os_version

    - name: Memory available - standard out lines
      ansible.builtin.debug:
        msg: "{{ os_version.stdout_lines }}"

    - name: Disk space - register variable
      ansible.builtin.shell: cat /etc/*ease
      changed_when: false
      register: os_version

    - name: Disk space - standard out lines
      ansible.builtin.debug:
        msg: "{{ os_version.stdout_lines }}"
