---
- name: Playbook test
  hosts: all
  tasks:

    - name: OS version - register variable
      ansible.builtin.shell:
        cmd: set -o pipefail && grep -iE "name|release" /etc/*release
      changed_when: false
      register: os_version

    - name: OS version - standard out
      ansible.builtin.debug:
        msg: "{{ os_version.stdout }}"

    - name: CPUs info - register variable
      ansible.builtin.shell:
        cmd: set -o pipefail && lscpu | grep -iE "CPU|Thread|Core|Socket"
      changed_when: false
      register: cpu_info

    - name: CPUs info - standard out lines
      ansible.builtin.debug:
        msg: "{{ cpu_info.stdout_lines }}"

    - name: CPU load - register variable
      ansible.builtin.command: uptime
      changed_when: false
      register: cpu_load

    - name: CPU load - standard out lines
      ansible.builtin.debug:
        msg: "{{ cpu_load.stdout_lines }}"

    - name: Memory available - register variable
      ansible.builtin.command: free -m
      changed_when: false
      register: mem_avail

    - name: Memory available - standard out lines
      ansible.builtin.debug:
        msg: "{{ mem_avail.stdout_lines }}"

    - name: Disk space - register variable
      ansible.builtin.command: df -h /
      changed_when: false
      register: disk_avail

    - name: Disk space - standard out lines
      ansible.builtin.debug:
        msg: "{{ disk_avail.stdout_lines }}"
