---
- name: QEMU-guest-agent remove
  hosts: all
  become: true
  tasks:

    - name: QEMU-guest-agent status - register variable
      ansible.builtin.command: systemctl status qemu-guest-agent
      changed_when: false
      ignore_errors: true
      register: remove_before

    - name: QEMU-guest-agent status BEFORE - standard out lines
      ansible.builtin.debug:
        msg: " == STATUS BEFORE ==  {{ remove_before.stdout_lines }}"

    - name: QEMU-guest-agent remove
      ansible.builtin.package:
        name: qemu-guest-agent
        state: absent

    - name: QEMU-guest-agent disable
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: false

    - name: QEMU-guest-agent status AFTER - register variable
      ansible.builtin.command: systemctl status qemu-guest-agent
      changed_when: false
      ignore_errors: true
      register: remove_after

    - name: QEMU-guest-agent status - standard out lines
      ansible.builtin.debug:
        msg: " == STATUS AFTER == {{ remove_after.stdout_lines }}"
