---
- name: QEMU-guest-agent install
  hosts: all
  become: true
  tasks:

    - name: QEMU-guest-agent status - register variable
      ansible.builtin.command: systemctl status qemu-guest-agent
      changed_when: false
      ignore_errors: true
      register: install_before

    - name: QEMU-guest-agent status BEFORE - standard out lines
      ansible.builtin.debug:
        msg: " == STATUS BEFORE ==  {{ install_before.stdout_lines }}"

    - name: QEMU-guest-agent install
      ansible.builtin.package:
        name: qemu-guest-agent
        state: present

    - name: QEMU-guest-agent enabled
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: true

    - name: QEMU-guest-agent start
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started

    - name: QEMU-guest-agent status AFTER - register variable
      ansible.builtin.command: systemctl status qemu-guest-agent
      changed_when: false
      ignore_errors: true
      register: install_after

    - name: QEMU-guest-agent status - standard out lines
      ansible.builtin.debug:
        msg: " == STATUS AFTER == {{ install_after.stdout_lines }}"
